-- ============================================================
-- Innov'Events Manager — Script de création de la base de données
-- PostgreSQL
-- ============================================================


-- ============================================================
-- TABLE : utilisateur
-- ============================================================
CREATE TABLE "utilisateur" (
  "id"                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email"                  VARCHAR(255) NOT NULL,
  "mot_de_passe"           VARCHAR(255) NOT NULL,
  "prenom"                 VARCHAR(100) NOT NULL,
  "nom"                    VARCHAR(100) NOT NULL,
  "username"               VARCHAR(100) NOT NULL,
  "role"                   VARCHAR(20)  NOT NULL,
  "est_actif"              BOOLEAN      NOT NULL DEFAULT true,
  "doit_changer_mdp"       BOOLEAN      NOT NULL DEFAULT false,
  "email_confirme"         BOOLEAN      NOT NULL DEFAULT false,
  "token_confirmation"     VARCHAR(255),
  "token_reset_mdp"        VARCHAR(255),
  "token_reset_expiration" TIMESTAMP,
  "demande_suppression"    BOOLEAN      NOT NULL DEFAULT false,
  "date_creation"          TIMESTAMP    NOT NULL DEFAULT now()
);

COMMENT ON COLUMN "utilisateur"."role" IS 'admin, employe, client';

ALTER TABLE "utilisateur"
  ADD CONSTRAINT unique_utilisateur_email    UNIQUE ("email"),
  ADD CONSTRAINT unique_utilisateur_username UNIQUE ("username"),
  ADD CONSTRAINT check_utilisateur_role      CHECK ("role" IN ('admin', 'employe', 'client'));


-- ============================================================
-- TABLE : prospect
-- ============================================================
CREATE TABLE "prospect" (
  "id"                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_entreprise"      VARCHAR(255) NOT NULL,
  "nom"                 VARCHAR(100) NOT NULL,
  "prenom"              VARCHAR(100) NOT NULL,
  "email"               VARCHAR(255) NOT NULL,
  "telephone"           VARCHAR(20)  NOT NULL,
  "lieu"                VARCHAR(255) NOT NULL,
  "type_evenement"      VARCHAR(50)  NOT NULL,
  "date_souhaitee"      DATE         NOT NULL,
  "nombre_participants" INT          NOT NULL,
  "description_besoin"  TEXT         NOT NULL,
  "statut"              VARCHAR(20)  NOT NULL DEFAULT 'à contacter',
  "converti"            BOOLEAN      NOT NULL DEFAULT false,
  "date_creation"       TIMESTAMP    NOT NULL DEFAULT now()
);

COMMENT ON COLUMN "prospect"."type_evenement" IS 'Séminaire, Conférence, Soirée d''entreprise, Autre';
COMMENT ON COLUMN "prospect"."statut"         IS 'à contacter, échoué';

ALTER TABLE "prospect"
  ADD CONSTRAINT check_prospect_statut       CHECK ("statut" IN ('à contacter', 'échoué')),
  ADD CONSTRAINT check_prospect_participants CHECK ("nombre_participants" > 0);


-- ============================================================
-- TABLE : client
-- ============================================================
CREATE TABLE "client" (
  "id"             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "utilisateur_id" INT          NOT NULL,
  "prospect_id"    INT          NOT NULL,
  "nom_entreprise" VARCHAR(255),
  "nom"            VARCHAR(100) NOT NULL,
  "prenom"         VARCHAR(100) NOT NULL,
  "email"          VARCHAR(255) NOT NULL,
  "telephone"      VARCHAR(20),
  "adresse"        VARCHAR(255),
  "date_creation"  TIMESTAMP    NOT NULL DEFAULT now()
);

ALTER TABLE "client"
  ADD CONSTRAINT unique_client_utilisateur UNIQUE ("utilisateur_id"),
  ADD CONSTRAINT unique_client_prospect    UNIQUE ("prospect_id");


-- ============================================================
-- TABLE : evenement
-- ============================================================
CREATE TABLE "evenement" (
  "id"             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id"      INT          NOT NULL,
  "prospect_id"    INT,
  "nom"            VARCHAR(255) NOT NULL,
  "date_debut"     TIMESTAMP    NOT NULL,
  "date_fin"       TIMESTAMP    NOT NULL,
  "lieu"           VARCHAR(255) NOT NULL,
  "statut"         VARCHAR(20)  NOT NULL DEFAULT 'brouillon',
  "visible"        BOOLEAN      NOT NULL DEFAULT false,
  "accord_client"  BOOLEAN      NOT NULL DEFAULT false,
  "image"          VARCHAR(255),
  "type_evenement" VARCHAR(50),
  "theme"          VARCHAR(100),
  "date_creation"  TIMESTAMP    NOT NULL DEFAULT now()
);

COMMENT ON COLUMN "evenement"."statut" IS 'brouillon, accepté, en cours, terminé, annulé';

ALTER TABLE "evenement"
  ADD CONSTRAINT check_evenement_statut CHECK ("statut" IN ('brouillon', 'accepté', 'en cours', 'terminé', 'annulé')),
  ADD CONSTRAINT check_evenement_dates  CHECK ("date_fin" > "date_debut");


-- ============================================================
-- TABLE : devis
-- ============================================================
CREATE TABLE "devis" (
  "id"                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id"          INT          NOT NULL,
  "evenement_id"       INT          NOT NULL,
  "createur_id"        INT          NOT NULL,
  "statut"             VARCHAR(30)  NOT NULL DEFAULT 'étude côté client',
  "montant_ht"         DECIMAL(10,2) NOT NULL,
  "tva_taux"           DECIMAL(5,2)  NOT NULL DEFAULT 20,
  "montant_tva"        DECIMAL(10,2) NOT NULL,
  "montant_ttc"        DECIMAL(10,2) NOT NULL,
  "fichier_pdf"        VARCHAR(255),
  "motif_modification" TEXT,
  "date_creation"      TIMESTAMP    NOT NULL DEFAULT now(),
  "date_envoi"         TIMESTAMP
);

COMMENT ON COLUMN "devis"."statut" IS 'étude côté client, accepté, refusé, modification, en cours';

ALTER TABLE "devis"
  ADD CONSTRAINT check_devis_statut     CHECK ("statut" IN ('étude côté client', 'accepté', 'refusé', 'modification', 'en cours')),
  ADD CONSTRAINT check_devis_montant_ht CHECK ("montant_ht" >= 0),
  ADD CONSTRAINT check_devis_tva_taux   CHECK ("tva_taux" >= 0);


-- ============================================================
-- TABLE : prestation
-- ============================================================
CREATE TABLE "prestation" (
  "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "devis_id"   INT          NOT NULL,
  "libelle"    VARCHAR(255) NOT NULL,
  "montant_ht" DECIMAL(10,2) NOT NULL
);

ALTER TABLE "prestation"
  ADD CONSTRAINT check_prestation_montant CHECK ("montant_ht" >= 0);


-- ============================================================
-- TABLE : note
-- ============================================================
CREATE TABLE "note" (
  "id"               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "auteur_id"        INT       NOT NULL,
  "evenement_id"     INT,
  "contenu"          TEXT      NOT NULL,
  "est_globale"      BOOLEAN   NOT NULL DEFAULT false,
  "date_creation"    TIMESTAMP NOT NULL DEFAULT now(),
  "date_modification" TIMESTAMP
);


-- ============================================================
-- TABLE : tache
-- ============================================================
CREATE TABLE "tache" (
  "id"           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evenement_id" INT          NOT NULL,
  "createur_id"  INT          NOT NULL,
  "assigne_id"   INT,
  "libelle"      VARCHAR(255) NOT NULL,
  "statut"       VARCHAR(20)  NOT NULL DEFAULT 'à faire',
  "date_creation" TIMESTAMP   NOT NULL DEFAULT now()
);

COMMENT ON COLUMN "tache"."statut" IS 'à faire, en cours, terminé';

ALTER TABLE "tache"
  ADD CONSTRAINT check_tache_statut CHECK ("statut" IN ('à faire', 'en cours', 'terminé'));


-- ============================================================
-- TABLE : avis
-- ============================================================
CREATE TABLE "avis" (
  "id"           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id"    INT       NOT NULL,
  "evenement_id" INT       NOT NULL,
  "valideur_id"  INT,
  "contenu"      TEXT      NOT NULL,
  "note"         INT       NOT NULL,
  "statut"       VARCHAR(20) NOT NULL DEFAULT 'en attente',
  "date_creation" TIMESTAMP NOT NULL DEFAULT now()
);

COMMENT ON COLUMN "avis"."note"   IS '1 à 5';
COMMENT ON COLUMN "avis"."statut" IS 'en attente, validé, refusé';

ALTER TABLE "avis"
  ADD CONSTRAINT check_avis_note   CHECK ("note" >= 1 AND "note" <= 5),
  ADD CONSTRAINT check_avis_statut CHECK ("statut" IN ('en attente', 'validé', 'refusé'));


-- ============================================================
-- TABLE : parametre
-- ============================================================
CREATE TABLE "parametre" (
  "id"    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cle"   VARCHAR(100) NOT NULL,
  "valeur" TEXT        NOT NULL
);

ALTER TABLE "parametre"
  ADD CONSTRAINT unique_parametre_cle UNIQUE ("cle");


-- ============================================================
-- CLES ETRANGERES
-- ============================================================

-- client
ALTER TABLE "client"
  ADD FOREIGN KEY ("utilisateur_id") REFERENCES "utilisateur" ("id") ON DELETE RESTRICT,
  ADD FOREIGN KEY ("prospect_id")    REFERENCES "prospect"    ("id") ON DELETE RESTRICT;

-- evenement
ALTER TABLE "evenement"
  ADD FOREIGN KEY ("client_id")   REFERENCES "client"   ("id") ON DELETE RESTRICT,
  ADD FOREIGN KEY ("prospect_id") REFERENCES "prospect" ("id") ON DELETE SET NULL;

-- devis
ALTER TABLE "devis"
  ADD FOREIGN KEY ("client_id")    REFERENCES "client"      ("id") ON DELETE RESTRICT,
  ADD FOREIGN KEY ("evenement_id") REFERENCES "evenement"   ("id") ON DELETE RESTRICT,
  ADD FOREIGN KEY ("createur_id")  REFERENCES "utilisateur" ("id") ON DELETE RESTRICT;

-- prestation
ALTER TABLE "prestation"
  ADD FOREIGN KEY ("devis_id") REFERENCES "devis" ("id") ON DELETE CASCADE;

-- note
ALTER TABLE "note"
  ADD FOREIGN KEY ("auteur_id")    REFERENCES "utilisateur" ("id") ON DELETE RESTRICT,
  ADD FOREIGN KEY ("evenement_id") REFERENCES "evenement"   ("id") ON DELETE CASCADE;

-- tache
ALTER TABLE "tache"
  ADD FOREIGN KEY ("evenement_id") REFERENCES "evenement"   ("id") ON DELETE CASCADE,
  ADD FOREIGN KEY ("createur_id")  REFERENCES "utilisateur" ("id") ON DELETE RESTRICT,
  ADD FOREIGN KEY ("assigne_id")   REFERENCES "utilisateur" ("id") ON DELETE SET NULL;

-- avis
ALTER TABLE "avis"
  ADD FOREIGN KEY ("client_id")    REFERENCES "client"      ("id") ON DELETE RESTRICT,
  ADD FOREIGN KEY ("evenement_id") REFERENCES "evenement"   ("id") ON DELETE RESTRICT,
  ADD FOREIGN KEY ("valideur_id")  REFERENCES "utilisateur" ("id") ON DELETE SET NULL;


-- ============================================================
-- INDEX
-- ============================================================
CREATE INDEX idx_utilisateur_email    ON "utilisateur" ("email");
CREATE INDEX idx_prospect_statut      ON "prospect"    ("statut");
CREATE INDEX idx_evenement_client     ON "evenement"   ("client_id");
CREATE INDEX idx_evenement_statut     ON "evenement"   ("statut");
CREATE INDEX idx_devis_client         ON "devis"       ("client_id");
CREATE INDEX idx_devis_evenement      ON "devis"       ("evenement_id");
CREATE INDEX idx_devis_statut         ON "devis"       ("statut");
CREATE INDEX idx_tache_assigne        ON "tache"       ("assigne_id");
CREATE INDEX idx_avis_statut          ON "avis"        ("statut");
CREATE INDEX idx_note_evenement       ON "note"        ("evenement_id");


-- ============================================================
-- DONNEES PAR DEFAUT
-- ============================================================
INSERT INTO "parametre" ("cle", "valeur") VALUES
  ('message_remerciement', 'Merci pour votre demande. Chloé vous recontactera dans les plus brefs délais pour discuter de votre projet.');